### ISSUE TITLE
API_AUDIENCE example is incorrect.

### ISSUE THREAD

**Issue by Sangtong** [Azure-Samples/ms-identity-python-webapi-azurefunctions#2]
1. API_AUDIENCE variable should be `https://funcapi.<tenantname>.onmicrosoft.com` instead, otherwise it will occur error code invalid_claims.

1. Could you please tell which Python version supports in the documentation because this did not support Python version 3.8?

**Comment by inspiralpatterns** [comment]
@Sangtong check [this](https://github.com/tiangolo/fastapi/issues/840#issuecomment-653839180) out, it worked for me in Python 3.8.
It is loosely inspired from this sample repo.

**Comment by Sangtong** [comment]
@inspiralpatterns Thank you for your reply.
